name: Build and upload the artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch: {}

jobs:
  build:
    name: build rust action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Build
        run: cargo build --release

      # the artifact to upload
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: zebclock
          path: target/release/libtest.d
